### ISSUE TITLE
Failed to load module script: The server responded with a non-JavaScript MIME type of “text/html”

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms#7]
This issue is raised in https://forum.groupdocs.com/t/groupdocs-editor/7835
Hi,
Application works just fine when it is ran on IIS express. But the problem occurs when deploying the published file to IIS.
Below is the exception that user is facing:
_Failed to load module script: The server responded with a non-JavaScript MIME type of "text / html". Strict MIME type checking is enforced for module scripts per HTML spec._

This is structure of virtual directory - 
![virtual directory](https://user-images.githubusercontent.com/15940608/70611139-87267180-1c26-11ea-94c6-ad93a209066c.png)
However, when I host application on IIS, I get this error in browser console - 
![console](https://user-images.githubusercontent.com/15940608/70612684-319f9400-1c29-11ea-8c04-60ab58792543.JPG)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, i'll try to reproduce this problem and will let you know when i'll find the solution.

**Comment by kegor** [comment]
@atirtahirgroupdocs, what do you think about the possibility to publish needed scripts from `Resources` folder as a solution?

![editor_iis_0](https://user-images.githubusercontent.com/17431807/70715454-61b76780-1cfb-11ea-914d-6fb67e3ec442.png)

**Comment by atirtahirgroupdocs** [comment]
@kegor I followed the above step. But still facing issues in console and application doesn't render.
![console](https://user-images.githubusercontent.com/15940608/70737636-d0fd7d80-1d34-11ea-9cb3-5eb4ee37d74a.JPG)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, probably i didn't met the same result because i used the same work-around as here https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/issues/47#issuecomment-534634022, what do you think about the using the same approach here?

![editor_iis_1](https://user-images.githubusercontent.com/17431807/70775950-dc7c9300-1d8c-11ea-95f6-2507e4167e87.png)

**Comment by atirtahirgroupdocs** [comment]
@kegor ,
Its mentioned in readme file that in order to render application in browser we have to follow this "http://localhost:8080/Editor" link. But application doesn't load with this url. However, it works perfectly for "http://localhost:8080/editor/". Can you please check this at your end? It doesn't even work for "http://localhost:8080/editor".
So a "/" and editor (with small e) is required in url in order to run it.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, sure, i'll check this.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, when you start the Editor for .NET Web Forms app in the VS (on IIS Express) there is not difference between all combinations of the url, so you just need /editor substring with/without finishing slash, with/without capital char, but on the stand-alone IIS which has a lot of options it depends on how you set up the app.
