### ISSUE TITLE
Which WYSIWYG editor is used in the project?

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms#9]
This issue is raised in https://forum.groupdocs.com/t/recommended-client-side-editor/7852
Hello,

Can you please tell which which WYSIWYG editor is used in this project? One of the customer tried two types of WYSIWYG editors _summernote_ and _trumbowyg_. Both give malformed HTML. So, please tell the exact editor used.
Thanks

**Comment by egorovpavel** [comment]
Hi, @atirtahirgroupdocs in this project we use our own simple WYSIWYG editor based on `contenteditable`. I believe that GroupDocs.Editor works with any WYSIWYG editor, however, I think that customer might have better luck with https://ckeditor.com/.
